namespace WpfApp1
{
    using System.Collections.Generic;
    using System.Windows;

    public class Person
    {
        public string Name { get; set; }
    }
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();


            var blabla = new List<Person>()
            {
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
                new Person{Name="Ramon" },
                new Person{Name="Mauro" },
            };

            grid.ItemsSource = blabla;
        }
    }
}
