//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     AssemblyInfo.tt
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Windows;

[assembly: AssemblyTitle("ServiceInsight")]
[assembly: AssemblyDescription("ServiceInsight")]
[assembly: AssemblyCopyright("Copyright 2013-2016 NServiceBus Ltd. All rights reserved.")]
[assembly: AssemblyProduct("ServiceInsight")]
[assembly: AssemblyCompany("NServiceBus Ltd.")]
[assembly: InternalsVisibleTo("ServiceInsight.Tests")]

[assembly:ThemeInfo(
    ResourceDictionaryLocation.None,
    //where theme specific resource dictionaries are located
    //(used if a resource is not found in the page,
    // or application resource dictionaries)
    ResourceDictionaryLocation.SourceAssembly
    //where the generic resource dictionary is located
    //(used if a resource is not found in the page,
    // app, or any theme specific resource dictionaries)
)]